"""initial schema with all tables

Revision ID: 3bdb70b225db
Revises: 
Create Date: 2025-11-17 13:40:24.054445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bdb70b225db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_table('companions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('persona', sa.Enum('listener', 'coach', 'planner', 'cheerleader', name='companionpersona'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('quick_prompts', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ui_config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companion_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('companion_id', sa.String(length=40), nullable=True),
    sa.Column('companion_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_sessions_user_id'), 'companion_sessions', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=32), nullable=False),
    sa.Column('sentiment_confidence', sa.Float(), nullable=False),
    sa.Column('sentiment_scores', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('sentiment_version', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_reason', sa.String(length=255), nullable=False),
    sa.Column('risk_triggers', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('risk_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_journal_user_day')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('companion_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='companionmessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['companion_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_messages_created_at'), 'companion_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_companion_messages_session_id'), 'companion_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companion_messages_session_id'), table_name='companion_messages')
    op.drop_index(op.f('ix_companion_messages_created_at'), table_name='companion_messages')
    op.drop_table('companion_messages')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_companion_sessions_user_id'), table_name='companion_sessions')
    op.drop_table('companion_sessions')
    op.drop_table('companions')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
